#!/usr/bin/env node
/**
 * Generate a new Nostr keypair for site Nostr API / signing (custodial server account).
 *
 *   node nostr/scripts/generate-account.cjs
 *   node nostr/scripts/generate-account.cjs --write-env .env.nostr
 *   node nostr/scripts/generate-account.cjs --write-env nostr/.env.local --force
 *
 * Env keys written:
 *   NOSTR_NSEC   — bech32 nsec (private; never commit)
 *   NOSTR_NPUB   — bech32 npub (public; safe to display)
 *
 * Legacy files may still use CLAWSTR_*; the server accepts either until you migrate.
 */
const fs = require("fs");
const path = require("path");
const { generatePrivateKey, getPublicKey, nip19 } = require("nostr-tools");

const REPO_ROOT = path.join(__dirname, "..", "..");

function parseArgs(argv) {
  const out = { writeEnv: null, force: false, json: false };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--write-env") {
      out.writeEnv = argv[++i];
      if (!out.writeEnv) {
        console.error("Missing path after --write-env");
        process.exit(1);
      }
    } else if (a === "--force") out.force = true;
    else if (a === "--json") out.json = true;
    else if (a === "-h" || a === "--help") {
      console.log(`Usage:
  node nostr/scripts/generate-account.cjs
  node nostr/scripts/generate-account.cjs --write-env <file>
  node nostr/scripts/generate-account.cjs --write-env <file> --force
  node nostr/scripts/generate-account.cjs --json

Options:
  --write-env <path>  Append NOSTR_NSEC and NOSTR_NPUB (refuses if file exists unless --force)
  --force             Overwrite existing NOSTR_* lines in target file when using --write-env
  --json              Print one JSON object on stdout (nsec, npub, pubkey_hex)`);
      process.exit(0);
    }
  }
  return out;
}

function resolveWritePath(relOrAbs) {
  if (path.isAbsolute(relOrAbs)) return relOrAbs;
  return path.join(REPO_ROOT, relOrAbs);
}

function upsertEnvBlock(filePath, nsec, npub, { force }) {
  const block = `
# Nostr (generated by nostr/scripts/generate-account.cjs — DO NOT COMMIT)
NOSTR_NSEC=${nsec}
NOSTR_NPUB=${npub}
`.trimStart();

  if (!fs.existsSync(filePath)) {
    fs.writeFileSync(filePath, block + "\n", { mode: 0o600 });
    try {
      fs.chmodSync(filePath, 0o600);
    } catch (_) {
      /* ignore on some FS */
    }
    return { created: true };
  }

  let text = fs.readFileSync(filePath, "utf8");
  const hasNostr = /(^|\n)NOSTR_NSEC=/.test(text) || /(^|\n)NOSTR_NPUB=/.test(text);
  if (hasNostr && !force) {
    const err = new Error(
      `File already contains NOSTR_* keys: ${filePath}\nUse --force to replace those lines.`
    );
    err.code = "EEXIST_KEYS";
    throw err;
  }

  if (hasNostr && force) {
    text = text.replace(/^NOSTR_NSEC=.*$/gm, "");
    text = text.replace(/^NOSTR_NPUB=.*$/gm, "");
    text = text.replace(/\n{3,}/g, "\n\n");
  }

  const sep = text.length && !text.endsWith("\n") ? "\n\n" : text.length ? "\n" : "";
  fs.writeFileSync(filePath, text.trimEnd() + sep + block + "\n", { mode: 0o600 });
  try {
    fs.chmodSync(filePath, 0o600);
  } catch (_) {}
  return { created: false };
}

function main() {
  const opts = parseArgs(process.argv.slice(2));
  const sk = generatePrivateKey();
  const pubkeyHex = getPublicKey(sk);
  const nsec = nip19.nsecEncode(sk);
  const npub = nip19.npubEncode(pubkeyHex);

  if (opts.json) {
    console.log(JSON.stringify({ nsec, npub, pubkey_hex: pubkeyHex }, null, 0));
    return;
  }

  if (opts.writeEnv) {
    const target = resolveWritePath(opts.writeEnv);
    const dir = path.dirname(target);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
    try {
      const { created } = upsertEnvBlock(target, nsec, npub, { force: opts.force });
      console.error(`Wrote keys to ${target} (${created ? "new file" : "updated"}).`);
    } catch (e) {
      if (e.code === "EEXIST_KEYS") {
        console.error(e.message);
        process.exit(1);
      }
      throw e;
    }
  }

  console.log(`
Nostr account (site Nostr API signing)
──────────────────────────────────────────
  npub (public):                             ${npub}
  pubkey (hex):                              ${pubkeyHex}

  nsec (PRIVATE — treat like a wallet seed): ${nsec}
──────────────────────────────────────────
Store NOSTR_NSEC only on the server secrets file (droplet) or local .env (never commit).
${opts.writeEnv ? "" : "Tip: npm run nostr:generate-account -- --write-env .env.nostr\n"}`);
}

main();
